Product_details=[
    {
        "prod_id":"1"
        ,"prod_name":"milk"
        ,"prod_cat":"diary"
        ,"unit_price":2
    },
     {
        "prod_id":"2"
        ,"prod_name":"yogurt"
        ,"prod_cat":"diary"
        ,"unit_price":3
    },
     {
        "prod_id":"3"
        ,"prod_name":"cheese"
        ,"prod_cat":"diary"
        ,"unit_price":4
    },
     {
        "prod_id":"4"
        ,"prod_name":"potato"
        ,"prod_cat":"veggies"
        ,"unit_price":5
    },
     {
        "prod_id":"5"
        ,"prod_name":"cabbage"
        ,"prod_cat":"veggies"
        ,"unit_price":6
    },
     {
        "prod_id":"6"
        ,"prod_name":"spinach"
        ,"prod_cat":"veggies"
        ,"unit_price":5
    },
     {
        "prod_id":"7"
        ,"prod_name":"orange"
        ,"prod_cat":"fruits"
        ,"unit_price":4
    },
     {
        "prod_id":"8"
        ,"prod_name":"papaya"
        ,"prod_cat":"fruits"
        ,"unit_price":3
    },
     {
        "prod_id":"9"
        ,"prod_name":"watermelon"
        ,"prod_cat":"fruits"
        ,"unit_price":2
    },
     {
        "prod_id":"10"
        ,"prod_name":"grapes"
        ,"prod_cat":"fruits"
        ,"unit_price":3
    },
     {
        "prod_id":"11"
        ,"prod_name":"pineapple"
        ,"prod_cat":"fruits"
        ,"unit_price":4
    },
     {
        "prod_id":"12"
        ,"prod_name":"dishwasher"
        ,"prod_cat":"kitchen"
        ,"unit_price":5
    },
     {
        "prod_id":"13"
        ,"prod_name":"kitchen_towel"
        ,"prod_cat":"kitchen"
        ,"unit_price":6
    },
     {
        "prod_id":"14"
        ,"prod_name":"perfume"
        ,"prod_cat":"cosmetics"
        ,"unit_price":5
    },
     {
        "prod_id":"15"
        ,"prod_name":"soap"
        ,"prod_cat":"cosmetics"
        ,"unit_price":4
    },
     {
        "prod_id":"16"
        ,"prod_name":"shampoo"
        ,"prod_cat":"cosmetics"
        ,"unit_price":3
    },
     {
        "prod_id":"17"
        ,"prod_name":"pen"
        ,"prod_cat":"office_supplies"
        ,"unit_price":2
    },
     {
        "prod_id":"18"
        ,"prod_name":"book"
        ,"prod_cat":"office_supplies"
        ,"unit_price":3
     },
     {
        "prod_id":"19"
        ,"prod_name":"markers"
        ,"prod_cat":"office_supplies"
        ,"unit_price":4
    },
     {
        "prod_id":"20"
        ,"prod_name":"pencil"
        ,"prod_cat":"office_supplies"
        ,"unit_price":5
     },
     {
        "prod_id":"21"
        ,"prod_name":"white_board"
        ,"prod_cat":"office_supplies"
        ,"unit_price":6
    },
     {
        "prod_id":"22"
        ,"prod_name":"doll_house"
        ,"prod_cat":"toys"
        ,"unit_price":5
    },
     {
        "prod_id":"23"
        ,"prod_name":"bulding_blocks"
        ,"prod_cat":"toys"
        ,"unit_price":4
    },
     {
        "prod_id":"24"
        ,"prod_name":"soccer_ball"
        ,"prod_cat":"sports"
        ,"unit_price":3
    },
     {
        "prod_id":"25"
        ,"prod_name":"bat"
        ,"prod_cat":"sports"
        ,"unit_price":2
    }
]